name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "scripts/**"
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint:check
