name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "tests/**"

jobs:
  api-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install NPM dependencies
        run: npm ci

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Prepare tests
        run: npm run test:update

      - name: Run tests
        run: npm run test:report

      - name: Add comment
        continue-on-error: true
        uses: mshick/add-pr-comment@a65df5f64fc741e91c59b8359a4bc56e57aaf5b1
        with:
          message-path: temp/report.md
